### ISSUE TITLE
Error: coudn't install npm package mturk-api@1.3.2

### ISSUE THREAD

**Issue by karnat1802** [VirtualLab/turkserver-meteor#66]
Keep getting this error when trying to install the package. 
![error](https://cloud.githubusercontent.com/assets/18597035/15270657/2fb9a78c-19f5-11e6-9110-536c4e12998d.JPG)

Just not being able to get around it.
Some help in getting around this will be hugely appreciated

**Comment by mizzao** [comment]
It seems like this may be caused by having a path that has a space in the name; e.g. is your Windows username `KARTHIK LASTNAME`? If so, this is a bug you should report to Meteor: https://github.com/meteor/meteor

Can you check this by trying to install other Meteor packages with npm dependencies?

**Comment by karnat1802** [comment]
My admin name has a first and last name? Do you recommend trying to install it after removing my last name ??
I am new to meteor so I am not aware of other packages with npm dependencies. Can you give me names of a few??

**Comment by mizzao** [comment]
It's just very rare for a username to have a space in it (your display name can have a space, but not the username in `C:\Users`) so it's possible that this is just a bug that hasn't been seen before, and in that case you should report it to Meteor.

Can you try the same process, but on a different Windows machine where the username is not of the form here (or just create a new account on the same machine)?

**Comment by karnat1802** [comment]
I tried creating a new account and running the app but it still shows the same error. Is there any way to debug this?? Or are there any other packages installed in my app that might be preventing it from getting installed?

**Comment by mizzao** [comment]
Hey @kgao, did you ever run into this issue when you were trying to install on Windows?

**Comment by kgao** [comment]
@mizzao Nope. Never had this issue. @karnat1802 I use node v5.8.0,  npm v3.7.3,  meteor 1.3.2.4 on Windows 10. Please make sure you have those installed properly.

**Comment by karnat1802** [comment]
Ok now I've got it installed. Seems like I was using an older version of nodejs and npm which was causing the error. Its resolved now. Thanks a ton @kgao and @mizzao

**Comment by karnat1802** [comment]
There is one more thing I wanted to ask. Is it absolutely mandatory to remove the autopublish and insecure packages to connect the app to the Mechanical Turk server ??

**Comment by mizzao** [comment]
Yes. Those are only for prototyping and even if you don't care about security at all, your app will absolutely not scale if the entire database is published to every client.

**Comment by karnat1802** [comment]
Oh okay! I guess I have to remove them and find a work around. Well thanks for helping me get the issue sorted.

**Comment by mizzao** [comment]
Instead of finding a workaround, how about just taking a look at how Meteor's publish/subscribe API works? https://docs.meteor.com/#/full/meteor_publish

The prototyping abilities of Meteor are really good for testing new research ideas, but you can't just expect to carry that over into running a fully fledged experiment.
